### ISSUE TITLE
Game Crashes At Bugsy Gym Battle

### ISSUE THREAD

**Issue by njdeliberto** [roukaour/pokecrystal#151] opened 2017-03-17 17:42 UTC
As soon as battle starts, game crashes

**Comment by njdeliberto** [comment] 2017-03-17 17:56
I'll just leave the game alone for a while. I know a lot of changes are being made day in/day out so maybe this one got lost in the shuffle/will be fixed when more is added.

Keep up the good work!

**Comment by njdeliberto** [comment] 2017-03-17 20:42
However, to address the current issue, the game crashes whenever a butterfree or beedrill enters battle

**Comment by roukaour** [comment] 2017-03-17 22:04
Duplicate of #150.

**Closed by roukaour** 2017-03-17 22:04 UTC
